name: Sync Copilot Instructions

on:
  schedule:
    - cron: "0 20 * * 4"
  workflow_dispatch:
    inputs:
      common_workflows_ref:
        description: "Branch to sync from"
        required: false
        type: string
        default: main

jobs:
  sync-copilot:
    uses: NHSDigital/eps-common-workflows/.github/workflows/sync_copilot.yml@f3d19a678a725917a5c59cae4d76db621bb7c9c7
    with:
      common_workflows_ref: ${{ inputs.common_workflows_ref }}
