name: Update Devcontainer Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4"

jobs:
  update_devcontainer_version:
    uses: NHSDigital/eps-common-workflows/.github/workflows/update-dev-container-version.yml@88f13d58fc823a78860dc8b9b0f666914fec2411
    permissions:
        contents: read
        packages: read
        pull-requests: write
    with:
      base_branch: main
    secrets:
      CREATE_PULL_REQUEST_APP_ID: ${{ secrets.CREATE_PULL_REQUEST_APP_ID }}
      CREATE_PULL_REQUEST_PEM: ${{ secrets.CREATE_PULL_REQUEST_PEM }}
